### ISSUE TITLE
Can you provide a demo for self-captured data?

### ISSUE THREAD

**Issue by nekoshadow1** [ymingxie/PARQ#1]
Hi Yiming, thanks for this amazing work! I am wondering if you can provide a similar demo that you have with NeuralRecon and PlanarRecon? Thanks a lot!

**Comment by ymingxie** [comment]
Hi, thanks for your interest in our work! 

Sure, I will add a demo script next week :)

Yiming

**Comment by nekoshadow1** [comment]
Much appreciated!

**Comment by ymingxie** [comment]
Demo files added :)

**Comment by nekoshadow1** [comment]
Thanks a lot! I will close this issue
