### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dwleeKAIST** [ymingxie/PARQ#2]
Can you provided the code how to generate 'average_scan2cad.txt' file?
The current code tries to read from the following path: '/work/vig/Datasets/ScanNet/average_scan2cad.txt'
Or, what does it look like and what's for?

**Comment by ymingxie** [comment]
Thanks for your interest in our work! I added this file to our codebase: [average_scan2cad.txt](https://github.com/ymingxie/PARQ/blob/main/data/average_scan2cad.txt)

Great catch, BTW :)

Yiming
